/**
 * Main code generator V2 - with branch-aware generation
 */

import type { IRWorkflow, GeneratedWorker, CodeGeneratorContext } from '../types.js';
import { NodeGeneratorFactory } from './node-generators.js';
import { BranchAwareGenerator } from './branch-aware-generator.js';

export class WorkerGeneratorV2 {
  private factory = new NodeGeneratorFactory();
  private branchAware = new BranchAwareGenerator();

  generate(workflow: IRWorkflow): GeneratedWorker {
    const indexTs = this.generateIndexTs(workflow);
    const wranglerToml = this.generateWranglerToml(workflow);
    const readme = this.generateReadme(workflow);

    return {
      indexTs,
      wranglerToml,
      readme,
    };
  }

  private generateIndexTs(workflow: IRWorkflow): string {
    const context: CodeGeneratorContext = {
      workflow,
      nodeOutputs: new Map(),
      indentLevel: 1,
    };

    const entryNode = workflow.nodes.find(
      (n) => n.id === workflow.executionGraph.entryNode
    );

    if (!entryNode) {
      throw new Error('No entry node found');
    }

    const nodeCode = this.branchAware.generate(workflow, context);

    const template = `/**
 * Transpiled n8n workflow: ${workflow.name}
 * Generated by n8n-transpiler (Branch-aware v2)
 *
 * Original workflow nodes: ${workflow.nodes.length}
 * Entry point: ${entryNode.name} (${entryNode.semanticType})
 */

export interface Env {
${this.generateEnvInterface(workflow)}
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    try {
      // Initialize execution context
      const context = {
        items: [] as Array<{ json: any }>,
        nodeOutputs: {} as Record<string, any>,
        loopState: {} as Record<string, any>,
        executionId: crypto.randomUUID(),
      };

${nodeCode}

      // Return final output
      return Response.json({
        success: true,
        items: context.items || items,
        executionId: context.executionId
      });

    } catch (error: any) {
      // Error handling
      console.error(JSON.stringify({
        event: 'workflow_error',
        workflow: '${workflow.name}',
        error: error.message,
        stack: error.stack,
      }));

      ${workflow.resources.queues.length > 0 ? `
      try {
        await env.ERROR_QUEUE.send({
          workflow: '${workflow.name}',
          error: {
            message: error.message,
            stack: error.stack,
          },
          timestamp: Date.now(),
        });
      } catch (queueError) {
        console.error('Failed to queue error:', queueError);
      }
      ` : ''}

      return Response.json({
        success: false,
        error: error.message
      }, { status: 500 });
    }
  },
${this.generateQueueHandler(workflow)}
};
`;

    return template;
  }

  private generateEnvInterface(workflow: IRWorkflow): string {
    const bindings: string[] = [];

    workflow.resources.secrets.forEach((secret) => {
      bindings.push(`  // ${secret.description}`);
      bindings.push(`  ${secret.bindingName}: { get(): Promise<string> };`);
    });

    workflow.resources.databases.forEach((db) => {
      bindings.push(`  ${db.bindingName}: Hyperdrive;`);
    });

    if (workflow.resources.ai) {
      bindings.push(`  AI: Ai;`);
    }

    workflow.resources.queues.forEach((queue) => {
      bindings.push(`  ${queue.bindingName}: Queue;`);
    });

    return bindings.join('\n');
  }

  private generateQueueHandler(workflow: IRWorkflow): string {
    if (workflow.resources.queues.length === 0) {
      return '';
    }

    return `
  async queue(batch: MessageBatch<any>, env: Env): Promise<void> {
    for (const message of batch.messages) {
      try {
        console.error(JSON.stringify({
          event: 'error_queue_processing',
          workflow: '${workflow.name}',
          errorData: message.body,
        }));

        message.ack();
      } catch (error) {
        console.error('Queue processing failed:', error);
        message.retry();
      }
    }
  }`;
  }

  private generateWranglerToml(workflow: IRWorkflow): string {
    const name = workflow.name.toLowerCase().replace(/[^a-z0-9-]/g, '-');

    let config = `# Generated wrangler.toml for: ${workflow.name}
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "${name}"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build.upload_source_maps]
enabled = true

`;

    if (workflow.resources.secrets.length > 0) {
      config += `# Secret bindings\n`;
      config += `# Configure secrets with: wrangler secret put <NAME>\n`;
      workflow.resources.secrets.forEach((secret) => {
        config += `[[secrets_store_secrets]]\n`;
        config += `binding = "${secret.bindingName}"\n`;
        config += `# Description: ${secret.description}\n\n`;
      });
    }

    if (workflow.resources.databases.length > 0) {
      config += `# Database bindings (Hyperdrive)\n`;
      config += `# Configure in Cloudflare dashboard first\n`;
      workflow.resources.databases.forEach((db) => {
        config += `[[hyperdrive]]\n`;
        config += `binding = "${db.bindingName}"\n`;
        config += `id = "<your-hyperdrive-id>"\n\n`;
      });
    }

    if (workflow.resources.ai) {
      config += `# Workers AI binding\n`;
      config += `[ai]\n`;
      config += `binding = "AI"\n\n`;
    }

    if (workflow.resources.queues.length > 0) {
      workflow.resources.queues.forEach((queue) => {
        config += `# Queue for ${queue.purpose}\n`;
        config += `[[queues.producers]]\n`;
        config += `binding = "${queue.bindingName}"\n`;
        config += `queue = "${name}-${queue.purpose}"\n\n`;
      });

      config += `[[queues.consumers]]\n`;
      config += `queue = "${name}-error-handling"\n`;
      config += `max_batch_size = 10\n`;
      config += `max_batch_timeout = 5\n\n`;
    }

    if (workflow.resources.cronTriggers.length > 0) {
      config += `# Cron triggers\n`;
      config += `[triggers]\n`;
      config += `crons = [\n`;
      workflow.resources.cronTriggers.forEach((trigger) => {
        config += `  "${trigger.cron}",  # ${trigger.nodeName}\n`;
      });
      config += `]\n\n`;
    }

    config += `# Environments\n`;
    config += `[env.staging]\n`;
    config += `name = "${name}-staging"\n\n`;

    config += `[env.production]\n`;
    config += `name = "${name}-production"\n`;

    return config;
  }

  private generateReadme(workflow: IRWorkflow): string {
    const secretSetup = workflow.resources.secrets
      .map((s) => `wrangler secret put ${s.bindingName}`)
      .join('\n');

    return `# ${workflow.name}

Transpiled n8n workflow deployed as Cloudflare Worker (v2 - Branch-aware).

## Setup

### 1. Install dependencies

\`\`\`bash
npm install
\`\`\`

### 2. Configure secrets

${workflow.resources.secrets.length > 0
  ? `\`\`\`bash\n${secretSetup}\n\`\`\``
  : 'No secrets required.'
}

### 3. Configure resources

${workflow.resources.databases.length > 0
  ? `- **Databases**: Create Hyperdrive bindings in Cloudflare dashboard\n${workflow.resources.databases.map(db => `  - ${db.bindingName}`).join('\n')}`
  : ''
}

${workflow.resources.queues.length > 0
  ? `- **Queues**: Queues will be auto-created on first deployment`
  : ''
}

## Deployment

\`\`\`bash
# Deploy to staging
wrangler deploy --env staging

# Deploy to production
wrangler deploy --env production
\`\`\`

## Local Development

\`\`\`bash
wrangler dev
\`\`\`

## Workflow Details

- **Original nodes**: ${workflow.nodes.length}
- **Entry point**: ${workflow.executionGraph.entryNode}
- **Version**: ${workflow.version}
- **Generator**: Branch-aware v2

### Supported nodes

${workflow.nodes.filter(n => this.factory.hasGenerator(n.semanticType)).length} of ${workflow.nodes.length} nodes supported

### Unsupported nodes

${workflow.nodes.filter(n => !this.factory.hasGenerator(n.semanticType)).map(n => `- ${n.name} (${n.originalType})`).join('\n') || 'All nodes supported'}
`;
  }
}
